apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-amfk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-amfk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-amfk
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-amfk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-amfk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ovhp-tenant/rhtap-demo-app/hacbs-test-project-amfk@sha256:5c3ab07ed422e8d9a2e59865c5ffac53b1f03350cbe9eec8c7b935fccece75b3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
